#konfigurasi
check-user-scopes: true
#server port
server:
  port: 9001

#spring konfigurasi postgres
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/dbjwt
#    username: dbjwt
#    password: root
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1
#    initialization-mode: never
#    platform: postgresql
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbjwt2
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate

---
#spring jackson
spring:
  jackson:
    serialization:
      indent_output: true


